apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: nginxapp
          image: nginx:latest
          ports:
            - containerPort: 80