apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploynginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginxapp
        image: nginx:1.14.1
        ports:
        - containerPort: 80
